### ISSUE TITLE
Falta de dados vindos da API

### ISSUE THREAD

**Issue by m-dantas** [SPURB/sispop#1]
Falta de informações encontrados:

- [x] ID's não retorna todas as imagens (Ex: 417).
- [x] Dados arquitetônicos.
- [x] Dados da fachada retorna os ID do registro e não a informação.

**Comment by hsolucas** [comment]
Foi criado um novo modelo específico para criação da ficha. Pode ser obtido pela seguinte api:

https://servicos.spurbanismo.sp.gov.br/triangulo/api/ficha/{idVistoria}
Exemplo: https://servicos.spurbanismo.sp.gov.br/triangulo/api/ficha/418

Sobre as imagens, nem sempre todas estarão presentes, a quantidade pode variar de 1 a 5.
